[package]
name = "xcache"
version = "0.1.0"
edition = "2024"
authors = ["Anekoique <ctolu01@gmail.com>"]

[dependencies]
xerrno = { workspace = true }
xmm = { workspace = true }
weak-map = { workspace = true }
xsync = { workspace = true }
xtask = { workspace = true, features = ["multitask"] }

log         = { workspace = true }
spin        = { workspace = true }
