[workspace]
resolver = "2"
members = ["xapi", "xcore"]
exclude = ["arceos", "apps"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = [
    "Azure-stars <Azure_stars@126.com>",
    "Yuekai Jia <equation618@gmail.com>",
]
homepage = "https://github.com/arceos-org/arceos"
repository = "https://github.com/arceos-org/starry-next"

[workspace.dependencies]
axfeat = { path = "arceos/api/axfeat", features = [
    "fs",
    "irq",
    "multitask",
    "net",
    "smp",
    "sched_rr",
] }

axconfig = { path = "arceos/modules/axconfig" }
axdriver = { path = "arceos/modules/axdriver" }
axhal = { path = "arceos/modules/axhal", features = [ "uspace", "rtc", "irq" ] }
axlog = { path = "arceos/modules/axlog" }
axmm = { path = "arceos/modules/axmm", features = [ "cow", "copy-from" ] }
axnet = { path = "arceos/modules/axnet" }
axns = { path = "arceos/modules/axns", features = [ "thread-local" ] }
axruntime = { path = "arceos/modules/axruntime" }
axsync = { path = "arceos/modules/axsync", features = [ "multitask" ] }
axtask = { path = "arceos/modules/axtask", features = [ "smp" ] }

axprocess = { path = "./modules/axprocess" }
axsignal = { path = "./modules/axsignal" }
axuspace = { path = "./modules/axuspace" }
axvma = { path = "./modules/axvma" }
page_cache = { path = "./modules/page_cache" }
axio = { path = "./modules/axio" }

axfs-ng = { path = "./arceos/modules/axfs-ng" }
axfs-ng-vfs = { path = "./arceos/crates/axfs-ng-vfs" }

axerrno = "0.1"
bitflags = "2.6"
cfg-if = "1.0"
inherit-methods-macro = "0.1.0"
linkme = "0.3"
linux-raw-sys = { version = "0.9.3", default-features = false, features = [
    "no_std",
    "general",
    "net",
    "prctl",
    "system",
    "loop_device",
] }
page_table_multiarch = "0.5.5"
memory_addr = "0.4"
spin = "0.9"

xcore = { path = "./xcore" }
xapi = { path = "./xapi" }

[package]
name = "starry"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
lwext4_rs = ["axfeat/lwext4_rs"]
ramdisk = ["axdriver/ramdisk"]

[dependencies]
axfeat.workspace = true

axconfig.workspace = true
axdriver.workspace = true
axfs-ng.workspace = true
axhal.workspace = true
axlog.workspace = true
axruntime.workspace = true
axsync.workspace = true
axtask.workspace = true
axmm.workspace = true
axio.workspace = true

axprocess.workspace = true
axsignal.workspace = true
axuspace.workspace = true
axvma.workspace = true
page_cache.workspace = true

axerrno.workspace = true
inherit-methods-macro.workspace = true
linkme.workspace = true
linux-raw-sys.workspace = true

xcore.workspace = true
xapi.workspace = true

spin.workspace = true
shlex = { version = "1.3.0", default-features = false }
syscalls = { git = "https://github.com/jasonwhite/syscalls.git", rev = "92624de", default-features = false }

[patch.crates-io]
page_table_multiarch = { path = "./arceos/crates/page_table_multiarch/page_table_multiarch" }
page_table_entry = { path = "./arceos/crates/page_table_multiarch/page_table_entry" }
axio = { path = "./modules/axio" }

[patch."https://github.com/arceos-org/axdriver_crates.git"]
axdriver_block = { path = "arceos/crates/axdriver_crates/axdriver_block", optional = true}