[package]
name = "xmm"
version.workspace = true
edition.workspace = true
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "Trusted frame and page-table mechanisms for StarryX"
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
default = []
copy-from = ["page_table_multiarch/copy-from"]

[dependencies]
xhal = { workspace = true, features = ["paging"] }
xalloc = { workspace = true }
xconfig = { workspace = true }

log         = { workspace = true }
xerrno     = { workspace = true }
lazyinit    = { workspace = true }
memory_addr = { workspace = true }
kspin       = { workspace = true }
page_table_multiarch = { workspace = true }
