PREFIX ?= riscv64-linux-gnu-
CC := $(PREFIX)gcc
HOST := $(patsubst %-gcc,%,$(CC))
STRIP := $(PREFIX)strip
DESTDIR ?= /code/sdcard/riscv/glibc

ifneq (,$(findstring riscv64,$(PREFIX)))
    ARCH := riscv64
    CROSS_TARGET := riscv64-linux-gnu
else ifneq (,$(findstring loongarch64,$(PREFIX)))
    ARCH := loongarch64
    CROSS_TARGET := loongarch64-linux-gnu
else
    $(error "Unknown ARCH! It should be riscv64 or loongarch64")
endif

all: busybox bash gcc


git: .PHONY
ifneq (,$(findstring riscv64,$(PREFIX)))
	cd zlib && CROSS_PREFIX=${CROSS_TARGET}- ./configure && make -j 16 && make DESTDIR=/usr/lib/gcc-cross/riscv64-linux-gnu/11 install
	cp /usr/lib/gcc-cross/riscv64-linux-gnu/11/usr/local/lib/libz.a /usr/lib/gcc-cross/riscv64-linux-gnu/11/
	cd git && ./configure --prefix=/usr --build=${CROSS_HOST} --host=${CROSS_TARGET} --with-gitconfig=/etc/gitconfig --with-python=python3 --without-iconv \
	    ac_cv_fread_reads_directories=yes ac_cv_snprintf_returns_bogus=no && make -j 16 && make install
else ifneq (,$(findstring loongarch64,$(PREFIX)))
	cd zlib && CROSS_PREFIX=${CROSS_TARGET}- ./configure && make -j 16 && make DESTDIR=/opt/gcc-13.2.0-loongarch64-linux-gnu/sysroot install
	cd git && ./configure --prefix=/usr --build=${CROSS_HOST} --host=${CROSS_TARGET} --with-gitconfig=/etc/gitconfig --with-python=python3 --without-iconv \
		ac_cv_fread_reads_directories=yes ac_cv_snprintf_returns_bogus=no && make -j 16 && make install
endif

busybox: .PHONY
	cp config/busybox-config-$(ARCH) busybox/.config
	make -C busybox CC="$(CC) -static" STRIP=$(STRIP) -j
	cp busybox/busybox $(DESTDIR)/

bash: .PHONY
	cd bash && \
	CC=$(CC) AR=$(PREFIX)ar RANLIB=$(PREFIX)ranlib \
	./configure \
		--host=$(HOST) \
		--enable-static-link \
		--without-bash-malloc \
		--disable-job-control && \
	make -j16 && \
	$(STRIP) bash && \
	cp bash $(DESTDIR)/
	
gcc: .PHONY
	cd gcc && ./contrib/download_prerequisites
	mkdir -p gcc-build
	cd gcc-build && \
	../gcc/configure \
		--host=$(CROSS_TARGET) \
		--target=$(CROSS_TARGET) \
		--prefix=/usr \
		--enable-languages=c \
		--disable-multilib \
		--disable-nls \
		--disable-libssp \
		--disable-libgomp \
		--disable-libquadmath \
		--disable-libstdcxx \
		--disable-threads \
		--disable-shared \
		--enable-static \
		--disable-bootstrap \
		--disable-checking \
		--without-headers \
		--with-newlib && \
	make -j16 all-gcc && \
	$(STRIP) gcc/xgcc gcc/cc1 && \
	cp gcc/xgcc $(DESTDIR)/gcc && \
	mkdir -p $(DESTDIR)/lib/gcc/$(CROSS_TARGET)/13.2.0 && \
	cp gcc/cc1 $(DESTDIR)/lib/gcc/$(CROSS_TARGET)/13.2.0/ && \
	mkdir -p $(DESTDIR)/libexec/gcc/$(CROSS_TARGET)/13.2.0 && \
	cp gcc/cc1 $(DESTDIR)/libexec/gcc/$(CROSS_TARGET)/13.2.0/
	
clean:
	make -C busybox clean
	make -C git clean
	make -C zlib clean
	rm -rf gcc-build
	

.PHONY: 
