PREFIX ?= riscv64-linux-gnu-
CC := $(PREFIX)gcc
HOST := $(patsubst %-gcc,%,$(CC))
STRIP := $(PREFIX)strip
DESTDIR ?= /code/sdcard/riscv/glibc

ifneq (,$(findstring riscv64,$(PREFIX)))
    ARCH := riscv64
    CROSS_TARGET := riscv64-linux-gnu
else ifneq (,$(findstring loongarch64,$(PREFIX)))
    ARCH := loongarch64
    CROSS_TARGET := loongarch64-linux-gnu
else
    $(error "Unknown ARCH! It should be riscv64 or loongarch64")
endif

all: busybox redis


git: .PHONY
ifneq (,$(findstring riscv64,$(PREFIX)))
	cd zlib && CROSS_PREFIX=${CROSS_TARGET}- ./configure && make -j 16 && make DESTDIR=/usr/lib/gcc-cross/riscv64-linux-gnu/11 install
	cp /usr/lib/gcc-cross/riscv64-linux-gnu/11/usr/local/lib/libz.a /usr/lib/gcc-cross/riscv64-linux-gnu/11/
	cd git && ./configure --prefix=/usr --build=${CROSS_HOST} --host=${CROSS_TARGET} --with-gitconfig=/etc/gitconfig --with-python=python3 --without-iconv \
	    ac_cv_fread_reads_directories=yes ac_cv_snprintf_returns_bogus=no && make -j 16 && make install
else ifneq (,$(findstring loongarch64,$(PREFIX)))
	cd zlib && CROSS_PREFIX=${CROSS_TARGET}- ./configure && make -j 16 && make DESTDIR=/opt/gcc-13.2.0-loongarch64-linux-gnu/sysroot install
	cd git && ./configure --prefix=/usr --build=${CROSS_HOST} --host=${CROSS_TARGET} --with-gitconfig=/etc/gitconfig --with-python=python3 --without-iconv \
		ac_cv_fread_reads_directories=yes ac_cv_snprintf_returns_bogus=no && make -j 16 && make install
endif

busybox: .PHONY
	cp config/busybox-config-$(ARCH) busybox/.config
	make -C busybox CC="$(CC) -static" STRIP=$(STRIP) -j
	cp busybox/busybox $(DESTDIR)/bin

bash: .PHONY
	cd bash && \
	CC=$(CC) AR=$(PREFIX)ar RANLIB=$(PREFIX)ranlib \
	./configure \
		--host=$(HOST) \
		--enable-static-link \
		--without-bash-malloc \
		--disable-job-control && \
	make -j16 && \
	$(STRIP) bash && \
	cp bash $(DESTDIR)/bin
	
gcc: .PHONY
	cd gcc && ./contrib/download_prerequisites
	mkdir -p gcc-build
	cd gcc-build && \
	../gcc/configure \
		--host=$(CROSS_TARGET) \
		--target=$(CROSS_TARGET) \
		--prefix=/usr \
		--enable-languages=c \
		--disable-multilib \
		--disable-nls \
		--disable-libssp \
		--disable-libgomp \
		--disable-libquadmath \
		--disable-libstdcxx \
		--disable-threads \
		--disable-shared \
		--enable-static \
		--disable-bootstrap \
		--disable-checking \
		--without-headers \
		--with-newlib && \
	make -j16 all-gcc && \
	$(STRIP) gcc/xgcc gcc/cc1 && \
	cp gcc/xgcc $(DESTDIR)/bin/gcc && \
	mkdir -p $(DESTDIR)/lib/gcc/$(CROSS_TARGET)/13.2.0 && \
	cp gcc/cc1 $(DESTDIR)/lib/gcc/$(CROSS_TARGET)/13.2.0/ && \
	mkdir -p $(DESTDIR)/libexec/gcc/$(CROSS_TARGET)/13.2.0 && \
	cp gcc/cc1 $(DESTDIR)/libexec/gcc/$(CROSS_TARGET)/13.2.0/

redis: .PHONY
	cd redis && \
	make distclean || true && \
	make -C deps/hiredis CC="$(CC)" AR="$(PREFIX)ar" RANLIB="$(PREFIX)ranlib" static && \
	make -C deps/linenoise CC="$(CC)" AR="$(PREFIX)ar" RANLIB="$(PREFIX)ranlib" && \
	cd deps/lua && make CC="$(CC)" AR="$(PREFIX)ar rc" RANLIB="$(PREFIX)ranlib" generic && cd ../.. && \
	make -C deps/hdr_histogram CC="$(CC)" AR="$(PREFIX)ar" RANLIB="$(PREFIX)ranlib" && \
	make -C deps/fpconv CC="$(CC)" AR="$(PREFIX)ar" RANLIB="$(PREFIX)ranlib" && \
	make -C src CC="$(CC)" \
		LDFLAGS="-static" \
		MALLOC=libc \
		BUILD_TLS=no \
		USE_SYSTEMD=no \
		OPTIMIZATION=-O2 \
		redis-server redis-cli && \
	$(STRIP) src/redis-server src/redis-cli && \
	mkdir -p $(DESTDIR)/bin && \
	cp src/redis-server $(DESTDIR)/bin/ && \
	cp src/redis-cli $(DESTDIR)/bin/
	
clean:
	rm -rf ./sdcard/riscv/*
	make -C busybox clean
	make -C git clean
	make -C redis clean
	rm -rf gcc-build
	

.PHONY: 
