[package]
name = "xvdso"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Linux-compatible vDSO component for StarryX"

[dependencies]
memory_addr.workspace = true
spin.workspace = true
xhal.workspace = true
xsync.workspace = true
xmas-elf = "0.10"
